name: "Hello World JS Action"
description: "Greet someone and record the time"

inputs:
  CLOUDFLARE_API_TOKEN:
    description: "Cloudflare token"
    required: true
  hostname:
    description: hostname
    required: true
  targetIp:
    description: targetIp
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
