name: "Hello World JS Action"
description: "Greet someone and record the time"

inputs:
  CLOUDFLARE_API_TOKEN:
    description: "Cloudflare token"
    required: true

outputs:
  time:
    description: "The time we greeted you"

runs:
  using: "node20"
  main: "dist/index.js"
