name: "Static deploy"
description: "Static deploy"

inputs:
  CLOUDFLARE_API_TOKEN:
    description: "Cloudflare token"
    required: true
  NETLIFY_TOKEN:
    description: "Netlify token"
    required: true
  dir:
    description: dir
    required: true
  hostname:
    description: hostname
    required: true
  targetIp:
    description: targetIp
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
